services:
  vods:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vods-server

    network_mode: "host"

    user: "${UID:-1000}:${GID:-1000}"  # <--- 添加这一行 (自动读取环境变量，或硬编码为 1000:1000)
    # ports:
      #- "8000:8000"
    environment:
      - USE_DIFY=true
      - DIFY_API_URL=http://192.168.0.52:80/v1/workflows/run
      - DIFY_API_KEY="在这里填入你新生成的安全API_KEY"
      
      - BASE_IMAGE_URL=http://192.168.0.52:82
      #- BASE_IMAGE_URL=http://127.0.0.1:8000
      #- BASE_IMAGE_URL=http://img.vods-local.com:8000

      - OPENCV_FFMPEG_CAPTURE_OPTIONS=rtsp_transport;tcp

        #- SERVICE_HOST=0.0.0.0
      - SERVICE_HOST=192.168.0.52
      - SERVICE_PORT=8000
      - OUTPUT_PATH=/app/output
      - DEFAULT_SKIP_FRAMES=20
      - MAX_CONCURRENT_TASKS=4
      - LOG_LEVEL=INFO

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - /home/pgh/work/docker_vds/src:/app/src
      # Mount output directory
      - /home/pgh/work/docker_vds/output:/app/output
      # Mount logs directory
      - /home/pgh/work/docker_vds/logs:/app/logs
      # Mount video files directory
      - /home/pgh/work/docker_vds/videos:/app/videos:ro
      # Mount suggestions file
      - /home/pgh/work/docker_vds/suggestions.yaml:/app/suggestions.yaml:ro
    restart: unless-stopped
    #networks:
      #- vods-network

networks:
  vods-network:
    driver: bridge
